# Generated by Django 4.2.20 on 2025-04-04 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='registered',
            field=models.BooleanField(default=False),
        ),
    ]
