# Generated by Django 4.2.20 on 2025-04-15 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_employee_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default='changeme123', max_length=128),
        ),
    ]
