# Generated by Django 4.2.20 on 2025-04-16 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_employee_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('engineer', 'Engineer'), ('teamleader', 'Team Leader'), ('departmentleader', 'Department Leader'), ('seniormanager', 'Senior Manager'), ('admin', 'Admin')], default='engineer', max_length=20),
        ),
    ]
