# Generated by Django 5.1.7 on 2025-04-25 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_healthcard_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='progress',
            field=models.CharField(choices=[('Stable', 'Stable'), ('Improving', 'Improving'), ('Getting worse', 'Getting worse')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vote',
            name='traffic_light',
            field=models.CharField(choices=[('Red', '🔴 Red'), ('Yellow', '🟡 Yellow'), ('Green', '🟢 Green')], max_length=6),
        ),
    ]
