# Generated by Django 5.1.7 on 2025-04-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_vote_comment_alter_vote_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcard',
            name='question',
            field=models.TextField(default='Delivering Value'),
            preserve_default=False,
        ),
    ]
