# Generated by Django 5.1.7 on 2025-04-26 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_healthcard_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthcard',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='healthcard',
            name='description',
        ),
        migrations.AddField(
            model_name='healthcard',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='healthcards', to='users.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='healthcard',
            name='green_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthcard',
            name='red_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthcard',
            name='yellow_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
