# Generated by Django 5.1.7 on 2025-04-26 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_healthcard_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthcard',
            name='green_description',
        ),
        migrations.RemoveField(
            model_name='healthcard',
            name='red_description',
        ),
        migrations.RemoveField(
            model_name='healthcard',
            name='yellow_description',
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('red_description', models.TextField()),
                ('yellow_description', models.TextField()),
                ('green_description', models.TextField()),
                ('healthcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='users.healthcard')),
            ],
        ),
    ]
