# Generated by Django 5.1.7 on 2025-04-27 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_healthcard_green_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthcard',
            name='question',
        ),
    ]
