# Generated by Django 5.2 on 2025-04-29 00:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_healthcard_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='is_from_questions',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traffic_light', models.CharField(choices=[('Red', '🔴 Red'), ('Yellow', '🟡 Yellow'), ('Green', '🟢 Green')], max_length=6)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='users.employee')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='users.question')),
            ],
            options={
                'unique_together': {('employee', 'question')},
            },
        ),
    ]
