# Generated by Django 5.1.7 on 2025-04-29 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_votingsession'),
        ('users', '0015_populate_questions'),
    ]

    operations = [
    ]
