# Generated by Django 5.1.7 on 2025-05-01 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_merge_0014_votingsession_0015_populate_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='is_from_questions',
        ),
        migrations.AddField(
            model_name='vote',
            name='actions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='users.question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='solution',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='progress',
            field=models.CharField(blank=True, choices=[('Stable', 'Stable'), ('Improving', 'Improving'), ('Getting worse', 'Getting worse')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='HealthCardTermsAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employee')),
                ('healthcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.healthcard')),
            ],
            options={
                'unique_together': {('employee', 'healthcard')},
            },
        ),
    ]
